#ifndef MAPPOINT_HPP
#define MAPPOINT_HPP

#include "SFML/Graphics.hpp"
#include "Game.hpp"

static sf::Vector2f MapPoint[FOOTHOLD_NUMBER] = {

	/*00MapPoint*/ {_X - NORMAL_FOOTHOLD_DIFF_PIXEL * 0 - SPECIAL_FOOTHOLD_DIFF_PIXEL * 0, _Y - NORMAL_FOOTHOLD_DIFF_PIXEL * 0 - SPECIAL_FOOTHOLD_DIFF_PIXEL * 0},

	// x좌표값만 감소합니다.
	// MapPoint[10]은 특별 발판

	/*01MapPoint*/ {_X - NORMAL_FOOTHOLD_DIFF_PIXEL * 1 - SPECIAL_FOOTHOLD_DIFF_PIXEL * 0, _Y - NORMAL_FOOTHOLD_DIFF_PIXEL * 0 - SPECIAL_FOOTHOLD_DIFF_PIXEL * 0},
	/*02MapPoint*/ {_X - NORMAL_FOOTHOLD_DIFF_PIXEL * 2 - SPECIAL_FOOTHOLD_DIFF_PIXEL * 0, _Y - NORMAL_FOOTHOLD_DIFF_PIXEL * 0 - SPECIAL_FOOTHOLD_DIFF_PIXEL * 0},
	/*03MapPoint*/ {_X - NORMAL_FOOTHOLD_DIFF_PIXEL * 3 - SPECIAL_FOOTHOLD_DIFF_PIXEL * 0, _Y - NORMAL_FOOTHOLD_DIFF_PIXEL * 0 - SPECIAL_FOOTHOLD_DIFF_PIXEL * 0},
	/*04MapPoint*/ {_X - NORMAL_FOOTHOLD_DIFF_PIXEL * 4 - SPECIAL_FOOTHOLD_DIFF_PIXEL * 0, _Y - NORMAL_FOOTHOLD_DIFF_PIXEL * 0 - SPECIAL_FOOTHOLD_DIFF_PIXEL * 0},
	/*05MapPoint*/ {_X - NORMAL_FOOTHOLD_DIFF_PIXEL * 5 - SPECIAL_FOOTHOLD_DIFF_PIXEL * 0, _Y - NORMAL_FOOTHOLD_DIFF_PIXEL * 0 - SPECIAL_FOOTHOLD_DIFF_PIXEL * 0},
	/*06MapPoint*/ {_X - NORMAL_FOOTHOLD_DIFF_PIXEL * 6 - SPECIAL_FOOTHOLD_DIFF_PIXEL * 0, _Y - NORMAL_FOOTHOLD_DIFF_PIXEL * 0 - SPECIAL_FOOTHOLD_DIFF_PIXEL * 0},
	/*07MapPoint*/ {_X - NORMAL_FOOTHOLD_DIFF_PIXEL * 7 - SPECIAL_FOOTHOLD_DIFF_PIXEL * 0, _Y - NORMAL_FOOTHOLD_DIFF_PIXEL * 0 - SPECIAL_FOOTHOLD_DIFF_PIXEL * 0},
	/*08MapPoint*/ {_X - NORMAL_FOOTHOLD_DIFF_PIXEL * 8 - SPECIAL_FOOTHOLD_DIFF_PIXEL * 0, _Y - NORMAL_FOOTHOLD_DIFF_PIXEL * 0 - SPECIAL_FOOTHOLD_DIFF_PIXEL * 0},
	/*09MapPoint*/ {_X - NORMAL_FOOTHOLD_DIFF_PIXEL * 9 - SPECIAL_FOOTHOLD_DIFF_PIXEL * 0, _Y - NORMAL_FOOTHOLD_DIFF_PIXEL * 0 - SPECIAL_FOOTHOLD_DIFF_PIXEL * 0},
	/*10MapPoint*/ {_X - NORMAL_FOOTHOLD_DIFF_PIXEL * 9 - SPECIAL_FOOTHOLD_DIFF_PIXEL * 1, _Y - NORMAL_FOOTHOLD_DIFF_PIXEL * 0 - SPECIAL_FOOTHOLD_DIFF_PIXEL * 0},

	// y좌표값만 감소합니다.
	// MapPoint[20]은 특별 발판

	/*11MapPoint*/ {_X - NORMAL_FOOTHOLD_DIFF_PIXEL * 9 - SPECIAL_FOOTHOLD_DIFF_PIXEL * 1, _Y - NORMAL_FOOTHOLD_DIFF_PIXEL * 0 - SPECIAL_FOOTHOLD_DIFF_PIXEL * 1},
	/*12MapPoint*/ {_X - NORMAL_FOOTHOLD_DIFF_PIXEL * 9 - SPECIAL_FOOTHOLD_DIFF_PIXEL * 1, _Y - NORMAL_FOOTHOLD_DIFF_PIXEL * 1 - SPECIAL_FOOTHOLD_DIFF_PIXEL * 1},
	/*13MapPoint*/ {_X - NORMAL_FOOTHOLD_DIFF_PIXEL * 9 - SPECIAL_FOOTHOLD_DIFF_PIXEL * 1, _Y - NORMAL_FOOTHOLD_DIFF_PIXEL * 2 - SPECIAL_FOOTHOLD_DIFF_PIXEL * 1},
	/*14MapPoint*/ {_X - NORMAL_FOOTHOLD_DIFF_PIXEL * 9 - SPECIAL_FOOTHOLD_DIFF_PIXEL * 1, _Y - NORMAL_FOOTHOLD_DIFF_PIXEL * 3 - SPECIAL_FOOTHOLD_DIFF_PIXEL * 1},
	/*15MapPoint*/ {_X - NORMAL_FOOTHOLD_DIFF_PIXEL * 9 - SPECIAL_FOOTHOLD_DIFF_PIXEL * 1, _Y - NORMAL_FOOTHOLD_DIFF_PIXEL * 4 - SPECIAL_FOOTHOLD_DIFF_PIXEL * 1},
	/*16MapPoint*/ {_X - NORMAL_FOOTHOLD_DIFF_PIXEL * 9 - SPECIAL_FOOTHOLD_DIFF_PIXEL * 1, _Y - NORMAL_FOOTHOLD_DIFF_PIXEL * 5 - SPECIAL_FOOTHOLD_DIFF_PIXEL * 1},
	/*17MapPoint*/ {_X - NORMAL_FOOTHOLD_DIFF_PIXEL * 9 - SPECIAL_FOOTHOLD_DIFF_PIXEL * 1, _Y - NORMAL_FOOTHOLD_DIFF_PIXEL * 6 - SPECIAL_FOOTHOLD_DIFF_PIXEL * 1},
	/*18MapPoint*/ {_X - NORMAL_FOOTHOLD_DIFF_PIXEL * 9 - SPECIAL_FOOTHOLD_DIFF_PIXEL * 1, _Y - NORMAL_FOOTHOLD_DIFF_PIXEL * 7 - SPECIAL_FOOTHOLD_DIFF_PIXEL * 1},
	/*19MapPoint*/ {_X - NORMAL_FOOTHOLD_DIFF_PIXEL * 9 - SPECIAL_FOOTHOLD_DIFF_PIXEL * 1, _Y - NORMAL_FOOTHOLD_DIFF_PIXEL * 8 - SPECIAL_FOOTHOLD_DIFF_PIXEL * 1},
	/*20MapPoint*/ {_X - NORMAL_FOOTHOLD_DIFF_PIXEL * 9 - SPECIAL_FOOTHOLD_DIFF_PIXEL * 1, _Y - NORMAL_FOOTHOLD_DIFF_PIXEL * 9 - SPECIAL_FOOTHOLD_DIFF_PIXEL * 1},

	// x좌표값만 증가합니다.
	// MapPoint[30]은 특별 발판

	/*21MapPoint*/ { MapPoint[9].x, MapPoint[20].y},
	/*22MapPoint*/ { MapPoint[8].x, MapPoint[20].y},
	/*23MapPoint*/ { MapPoint[7].x, MapPoint[20].y},
	/*24MapPoint*/ { MapPoint[6].x, MapPoint[20].y},
	/*25MapPoint*/ { MapPoint[5].x, MapPoint[20].y},
	/*26MapPoint*/ { MapPoint[4].x, MapPoint[20].y},
	/*27MapPoint*/ { MapPoint[3].x, MapPoint[20].y},
	/*28MapPoint*/ { MapPoint[2].x, MapPoint[20].y},
	/*29MapPoint*/ { MapPoint[1].x, MapPoint[20].y},
	/*30MapPoint*/ { MapPoint[0].x, MapPoint[20].y},

	// y좌표값만 증가합니다.

	/*31MapPoint*/ {MapPoint[0].x, MapPoint[19].y},
	/*32MapPoint*/ {MapPoint[0].x, MapPoint[18].y},
	/*33MapPoint*/ {MapPoint[0].x, MapPoint[17].y},
	/*34MapPoint*/ {MapPoint[0].x, MapPoint[16].y},
	/*35MapPoint*/ {MapPoint[0].x, MapPoint[15].y},
	/*36MapPoint*/ {MapPoint[0].x, MapPoint[14].y},
	/*37MapPoint*/ {MapPoint[0].x, MapPoint[13].y},
	/*38MapPoint*/ {MapPoint[0].x, MapPoint[12].y},
	/*39MapPoint*/ {MapPoint[0].x, MapPoint[11].y},


};

#endif